# Generated by Django 5.0.6 on 2024-07-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='chinese',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='idiomSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleSentence', models.TextField()),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phrases.idiom')),
            ],
        ),
    ]
